
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author daniel
 */
public class InterfazGrafica extends javax.swing.JFrame {
    private CPURegister cpu = new CPURegister(0,0,0,0,0,0,0); 
    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        AX = new javax.swing.JTextField();
        BX = new javax.swing.JTextField();
        CX = new javax.swing.JTextField();
        DX = new javax.swing.JTextField();
        PC = new javax.swing.JTextField();
        AC = new javax.swing.JTextField();
        IR = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Start = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "RESERVE", "RESERVE"},
                {"2", "RESERVE", "RESERVE"},
                {"3", "RESERVE", "RESERVE"},
                {"4", "RESERVE", "RESERVE"},
                {"5", "RESERVE", "RESERVE"},
                {"6", "RESERVE", "RESERVE"},
                {"7", "RESERVE", "RESERVE"},
                {"8", "RESERVE", "RESERVE"},
                {"9", "RESERVE", "RESERVE"},
                {"10", "RESERVE", "RESERVE"},
                {"11", "RESERVE", "RESERVE"},
                {"12", "RESERVE", "RESERVE"},
                {"13", "RESERVE", "RESERVE"},
                {"14", "RESERVE", "RESERVE"},
                {"15", "RESERVE", "RESERVE"},
                {"16", "RESERVE", "RESERVE"},
                {"17", "RESERVE", "RESERVE"},
                {"18", "RESERVE", "RESERVE"},
                {"19", "RESERVE", "RESERVE"},
                {"20", "RESERVE", "RESERVE"},
                {"21", null, null},
                {"22", null, null},
                {"23", null, null},
                {"24", null, null},
                {"25", null, null},
                {"26", null, null},
                {"27", null, null},
                {"28", null, null},
                {"29", null, null},
                {"30", null, null},
                {"31", null, null},
                {"32", null, null},
                {"33", null, null},
                {"34", null, null},
                {"35", null, null},
                {"36", null, null},
                {"37", null, null},
                {"38", null, null},
                {"39", null, null},
                {"40", null, null},
                {"41", null, null},
                {"42", null, null},
                {"43", null, null},
                {"44", null, null},
                {"45", null, null},
                {"46", null, null},
                {"47", null, null},
                {"48", null, null},
                {"49", null, null},
                {"50", null, null},
                {"51", null, null},
                {"52", null, null},
                {"53", null, null},
                {"54", null, null},
                {"55", null, null},
                {"56", null, null},
                {"57", null, null},
                {"58", null, null},
                {"59", null, null},
                {"60", null, null},
                {"61", null, null},
                {"62", null, null},
                {"63", null, null},
                {"64", null, null},
                {"65", null, null},
                {"66", null, null},
                {"67", null, null},
                {"68", null, null},
                {"69", null, null},
                {"70", null, null},
                {"71", null, null},
                {"72", null, null},
                {"73", null, null},
                {"74", null, null},
                {"75", null, null},
                {"76", null, null},
                {"77", null, null},
                {"78", null, null},
                {"79", null, null},
                {"80", null, null},
                {"81", null, null},
                {"82", null, null},
                {"83", null, null},
                {"84", null, null},
                {"85", null, null},
                {"86", null, null},
                {"87", null, null},
                {"88", null, null},
                {"89", null, null},
                {"90", null, null},
                {"91", null, null},
                {"92", null, null},
                {"93", null, null},
                {"94", null, null},
                {"95", null, null},
                {"96", null, null},
                {"97", null, null},
                {"98", null, null},
                {"99", null, null},
                {"100", null, null}
            },
            new String [] {
                "Line", "Code", "Binary"
            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel1.setText("AX");

        jLabel2.setText("BX");

        jLabel3.setText("CX");

        jLabel4.setText("DX");

        AX.setEditable(false);
        AX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AXActionPerformed(evt);
            }
        });

        BX.setEditable(false);
        BX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BXActionPerformed(evt);
            }
        });

        CX.setEditable(false);
        CX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CXActionPerformed(evt);
            }
        });

        DX.setEditable(false);
        DX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DXActionPerformed(evt);
            }
        });

        PC.setEditable(false);
        PC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PCActionPerformed(evt);
            }
        });

        AC.setEditable(false);
        AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACActionPerformed(evt);
            }
        });

        IR.setEditable(false);
        IR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IRActionPerformed(evt);
            }
        });

        jLabel5.setText("PC");

        jLabel6.setText("AC");

        jLabel7.setText("IR");

        Start.setText("START");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AX, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(PC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(12, 12, 12)
                                    .addComponent(jLabel1))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BX, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(CX, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(DX, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel6)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(AC, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(IR, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Start)))
                        .addGap(82, 82, 82))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Start)
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BXActionPerformed
        // TODO add your handling code here:
        cpu.getBX();
    }//GEN-LAST:event_BXActionPerformed

    private void AXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AXActionPerformed
        
        
    }//GEN-LAST:event_AXActionPerformed

    private void CXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CXActionPerformed
        // TODO add your handling code here:
        cpu.getCX();
    }//GEN-LAST:event_CXActionPerformed

    private void DXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DXActionPerformed
        cpu.getDX();        // TODO add your handling code here:
    }//GEN-LAST:event_DXActionPerformed

    private void PCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PCActionPerformed
        // TODO add your handling code here:
        cpu.getPC();
    }//GEN-LAST:event_PCActionPerformed

    private void ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACActionPerformed
        // TODO add your handling code here:
        cpu.getAC();
    }//GEN-LAST:event_ACActionPerformed

    private void IRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IRActionPerformed
        // TODO add your handling code here:
        cpu.getIR();
    }//GEN-LAST:event_IRActionPerformed

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
        cpu = new CPURegister(0,0,0,0,0,0,0);
        cpu.runInstruction("file.asm");
        AX.setText(Integer.toString(cpu.getAX()));
        BX.setText(Integer.toString(cpu.getBX()));
        CX.setText(Integer.toString(cpu.getCX()));
        DX.setText(Integer.toString(cpu.getDX()));
        AC.setText(Integer.toString(cpu.getAC()));
        PC.setText(Integer.toString(cpu.getPC()));
        IR.setText(Integer.toString(cpu.getIR()));
        
        
        
    }//GEN-LAST:event_StartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGrafica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AC;
    private javax.swing.JTextField AX;
    private javax.swing.JTextField BX;
    private javax.swing.JTextField CX;
    private javax.swing.JTextField DX;
    private javax.swing.JTextField IR;
    private javax.swing.JTextField PC;
    private javax.swing.JButton Start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
